INSERT INTO USER (ID, NAME, CREATED_DATE) VALUES (ID.NEXTVAL, '추호년1', TO_CHAR(SYSDATE,'yyyyMMdd'));
INSERT INTO USER (ID, NAME, CREATED_DATE) VALUES (ID.NEXTVAL, '추호년2', TO_CHAR(SYSDATE,'yyyyMMdd'));
INSERT INTO USER (ID, NAME, CREATED_DATE) VALUES (ID.NEXTVAL, '추호년3', TO_CHAR(SYSDATE,'yyyyMMdd'));
INSERT INTO USER (ID, NAME, CREATED_DATE) VALUES (ID.NEXTVAL, '추호년4', TO_CHAR(SYSDATE,'yyyyMMdd'));
INSERT INTO USER (ID, NAME, CREATED_DATE) VALUES (ID.NEXTVAL, '추호년5', TO_CHAR(SYSDATE,'yyyyMMdd'));